library(tm)


review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_1_1000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_1001_2000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_2001_4000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_4001_5000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_5001_7000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_7001_10000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_1_10000.csv") 

review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_10001_11000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_11001_12000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_12001_13000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_13001_13500.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_13501_13609.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_13610_14000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_14001_14500.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_14501_15000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_15001_15500.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_15501_16000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_16001_17000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_17001_18000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_18001_19000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_19001_20000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)


review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_20001_22000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_22001_24000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_24001_24162.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_24163_25000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_25001_26000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_26001_30000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_20001_30000.csv") 

review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_30001_36000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_36001_38000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_38001_39000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_39001_41000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_30001_41000.csv") 


review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_41001_42000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_42001_44000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_44001_46000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_46001_49000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_49001_51000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_41001_51000.csv") 

review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_51001_53000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_53001_55000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_55001_57000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_57001_58000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_58001_59000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_59001_60000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_51001_60000.csv") 


review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_60001_61000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_61001_62000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_62001_63000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_63001_65000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_65001_67000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_67001_68000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_68001_70000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_60001_70000.csv") 

review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_70001_72000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-review_data
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_72001_74000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_74001_76000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_76001_78000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_78001_80000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
review_data <- read.csv("./reviewdata/SAMPLE_MOVIE_DATA_DAUM_80001_81000.csv",header=TRUE, stringsAsFactors=FALSE)
a<-rbind(a,review_data)
write.csv(a,"./reviewdata/SAMPLE_MOVIE_DATA_DAUM_70001_81000.csv")
